Feat/profile page widgets
abelard-l/twitter-demo-frontend pull request #2
Opened 2018-06-20 08:30 UTC by abelard-l

https://build-yhaldfokkr.now.sh

2018-06-20 21:49 UTC, imevro requested changes

2018-06-20 21:49 UTC, evgenyrodionov commented on src/Main/CountryTrends.js
> +import BlueLinkSm from "../UI/BlueLinkSm";
мне кажется что цвет и размер это модификаторы которые можно передавать пропами

2018-06-20 21:49 UTC, evgenyrodionov commented on src/Main/CountryTrends.js
> +    <Trend to="./trends/Trident" description="6,136 Tweets">
почему у тебя ссылки указывают как будто на файловую систему?

плюс description можно превратить в какой-нибудь count, зачем Tweets постоянно таскать

2018-06-20 21:49 UTC, evgenyrodionov commented on src/UI/BlueLinkSm.js
> +  <BlueLinkSm to={to}>{children}</BlueLinkSm>
зачем ты делаешь эту прокладку, если можешь сразу экспортить ск?

2018-06-22 21:11 UTC, imevro requested changes

2018-06-22 21:11 UTC, evgenyrodionov commented on src/Main/CountryTrends.js
> +const TrendTweetsCount = TrendDescription;
что это значит

2018-06-22 21:11 UTC, evgenyrodionov commented on src/Main/CountryTrends.js
> +    {tweets && (
count мб?

2018-06-25 15:01 UTC, imevro approved these changes

2018-06-25 15:01 UTC, merged

2018-06-25 15:01 UTC, evgenyrodionov commented
Не забудь сделать гит пулл перед тем как стартовать новые ветки от мастера

Если уже делал новую ветку от этой, то коммитни изменения, сделай новую от мастера и туда черри-пиком и забери коммиты

Напиши мне в телеграм с ссылкой на этот пуллреквест, добавлю в курсач и второй этап